before:
  hooks:
    - go mod download
builds:
  - id binary
  - env:
      - CGO_ENABLED=0
    id: olm-bundle
    main: cmd/olm-bundle/main.go
    binary: bin/olm-bundle
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Tag }} -X main.commit={{ .Commit }}
archives:
  format: binary
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  draft: false
